FROM node:lts-alpine AS build

WORKDIR /usr/src/app

# Add the source code to app
COPY ./ /usr/src/app/

RUN npm install @11ty/eleventy -g
# Install all the dependencies
RUN npm install --force

# Generate the build of the application
RUN npx eleventy

# Multistage build
FROM nginx:latest

COPY --from=build /usr/src/app/dist /usr/share/nginx/html
COPY --from=build /usr/src/app/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
