[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[build]
  publish = "_site"
  command = "DEBUG=* eleventy"
  
  